- name: Configure Cisco Switch
  hosts: cisco_switches
  gather_facts: no
  connection: network_cli

  tasks:
   - name: Ensure VLAN 2 exists
     cisco.ios.ios_config:
      lines:
        - "vlan 4"
        - "name Buisness"
      match: none
   - name: Set ip address on VLAN 4
     cisco.ios.ios_config:
      lines:
        - "int vlan 4"
        - "ip address 10.55.4.1 255.255.255.0"
        - "exit"
      match: none
   - name: Create access-list group 
     cisco.ios.ios_config:
      lines:
        - "ip access-list "
        - "network 10.55.4.0 255.255.255.0"
        - "dns-server 8.8.8.8"
        - "default-router 10.55.4.1"
        - "domain-name BUSnetwork.local"
      match: none
   

