---
- name: configure router
  hosts: cisco_router
  gather_facts: no
  connection: local 

  tasks:
    - name: show router version 
      cisco.ios.ios_command:
        commands:
          - show ip int br
          - show cdp neighbors
      register: command_output 
    - name: Debug command output
      debug:
        var: command_output
    - name: Print output to file
      ansible.builtin.copy:
        content: "{{command_output.stdout}}"
        dest: /root/playbooks/file.txt
      delegate_to: localhost
