- name: set timezone and configure timesyncd
  hosts: "*"
  become: yes
  tasks:
  - name: set timezone 
    shell: timedatectl set-timezone America/New_York 

  - name: Make sure timesyncd is stopped 
    systemd: 
      name: systemd-timesyncd.service
      state: stopped 
  
  - name: Make sure timesyncd is  started
    systemd:
      name: systemd-timesyncd.service 
      state: started 

 
